package provider

const (
	errProviderDataSummary = "provider data"
	errProviderDataNil      = "provider data or Jira client is nil"

	errCreateJiraProject            = "create jira project"
	errReadJiraProject              = "read jira project"
	errUpdateJiraProject            = "update jira project"
	errDeleteJiraProject            = "delete jira project"
	errImportJiraProject            = "import jira project"
	errCreateJiraPermissionScheme   = "create jira permission scheme"
	errReadJiraPermissionScheme     = "read jira permission scheme"
	errUpdateJiraPermissionScheme   = "update jira permission scheme"
	errDeleteJiraPermissionScheme   = "delete jira permission scheme"
	errImportJiraPermissionScheme   = "import jira permission scheme"
	errCreateJiraPermissionGrant    = "create jira permission grant"
	errReadJiraPermissionGrant      = "read jira permission grant"
	errDeleteJiraPermissionGrant    = "delete jira permission grant"
	errImportJiraPermissionGrant    = "import jira permission grant"
	errAssignPermissionScheme       = "assign permission scheme"
	errReadProjectPermissionScheme  = "read project permission scheme"
	errUpdateProjectPermissionScheme = "update project permission scheme"
	errSchemeID                     = "scheme_id"
	errImport                       = "import"
	errCreateJiraGroup              = "create jira group"
	errReadJiraGroup                = "read jira group"
	errDeleteJiraGroup              = "delete jira group"
	errActor                        = "actor"
	errAddProjectRoleActor          = "add project role actor"
	errReadProjectRoleActor         = "read project role actor"
	errDeleteProjectRoleActor       = "delete project role actor"
	errAssignWorkflowScheme         = "assign workflow scheme"
	errReadWorkflowSchemeAttachment = "read workflow scheme attachment"
	errHolder                       = "holder"
	errHolderType                   = "holder_type"
)

const msgSchemaDescriptionEmpty = "Schema.MarkdownDescription should not be empty"
